version: '3.8'
services:
  frontend:
    build:
      context: ./frontend-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  catalog:
    build:
      context: ./catalog-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
  order:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"